[workspace]
members = ["host", "methods"]
resolver = "2"

[workspace.dependencies]
risc0-zkvm = "1.1"
risc0-build = "1.1"
bincode = "1.3"

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
