[package]
name = "ssz-zkvm-methods"
version.workspace = true
edition.workspace = true

[build-dependencies]
risc0-build = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]

[lib]
path = "src/lib.rs"
